import 'dart:convert';
import 'dart:io';
import 'package:file_picker/file_picker.dart';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'package:video_player/video_player.dart';

class Cue { int index; Duration start,end; String text, translated; Cue(this.index,this.start,this.end,this.text,[this.translated='']); }
Duration ts(String s){ final p=s.replaceAll(',', '.').split(':'); return Duration(hours:int.parse(p[0]),minutes:int.parse(p[1]),seconds:double.parse(p[2]).floor(),milliseconds:(double.parse(p[2]).remainder(1)*1000).round()); }
List<Cue> parse(String raw){ final blocks=raw.replaceAll('\r','').trim().split(RegExp(r'\n\s*\n')); final out=<Cue>[]; for(final b in blocks){final l=b.split('\n'); if(l.length<2)continue; final ti=l.indexWhere((x)=>x.contains('-->')); if(ti<0)continue; final t=l[ti].split('-->'); try{out.add(Cue(out.length+1,ts(t[0].trim()),ts(t[1].trim().split(' ').first),l.sublist(ti+1).join('\n')));}catch(_){}} return out; }
String makeSrt(List<Cue> c){String f(Duration d)=>'${d.inHours.toString().padLeft(2,'0')}:${(d.inMinutes%60).toString().padLeft(2,'0')}:${(d.inSeconds%60).toString().padLeft(2,'0')},${(d.inMilliseconds%1000).toString().padLeft(3,'0')}'; return c.map((x)=>'${x.index}\n${f(x.start)} --> ${f(x.end)}\n${x.translated.isEmpty?x.text:x.translated}').join('\n\n');}
void main()=>runApp(const App());
class App extends StatefulWidget{const App({super.key});State<App> createState()=>_AppState();}
class _AppState extends State<App>{VideoPlayerController? v; List<Cue> cues=[]; String url=''; bool translated=false,busy=false; String status='Pilih video dan subtitle SRT/VTT.'; Cue? current;
Future<void> pickVideo()async{final r=await FilePicker.platform.pickFiles(type:FileType.video);if(r?.files.single.path==null)return; await v?.dispose();v=VideoPlayerController.file(File(r!.files.single.path!));await v!.initialize();v!.addListener(()=>setState((){current=cues.where((c)=>v!.value.position>=c.start&&v!.value.position<=c.end).firstOrNull;}));setState((){});}
Future<void> pickSub()async{final r=await FilePicker.platform.pickFiles(type:FileType.custom,allowedExtensions:['srt','vtt']);if(r?.files.single.path==null)return;final text=await File(r!.files.single.path!).readAsString();setState((){cues=parse(text);status='${cues.length} subtitle ditemukan.';});}
Future<void> translateAll()async{if(cues.isEmpty||url.trim().isEmpty){setState(()=>status='Isi URL backend terlebih dahulu.');return;}setState((){busy=true;status='Menerjemahkan...';});try{for(int i=0;i<cues.length;i+=10){final batch=cues.skip(i).take(10).map((c)=>{'id':c.index,'text':c.text}).toList();final res=await http.post(Uri.parse('${url.replaceAll(RegExp(r'/$'),'')}/translate'),headers:{'Content-Type':'application/json'},body:jsonEncode({'items':batch}));if(res.statusCode>=300)throw Exception(res.body);final arr=jsonDecode(res.body)['translations'] as List;for(final x in arr){final c=cues.firstWhere((c)=>c.index==x['id']);c.translated=x['translation']??'';}setState(()=>status='${(i+batch.length).clamp(0,cues.length)}/${cues.length} selesai');}setState(()=>translated=true);}catch(e){setState(()=>status='Gagal: $e');}finally{setState(()=>busy=false);}}
Future<void> save()async{final bytes=utf8.encode(makeSrt(cues));await FilePicker.platform.saveFile(fileName:'translated_indonesia.srt',bytes:bytes);}
@override void dispose(){v?.dispose();super.dispose();}
@override Widget build(BuildContext c){return MaterialApp(theme:ThemeData.dark(useMaterial3:true).copyWith(colorScheme:ColorScheme.fromSeed(seedColor:Colors.red,brightness:Brightness.dark)),home:Scaffold(appBar:AppBar(title:const Text('AV Translator'),actions:[IconButton(onPressed:cues.isEmpty?null:save,icon:const Icon(Icons.download))]),body:ListView(padding:const EdgeInsets.all(16),children:[if(v!=null&&v!.value.isInitialized)AspectRatio(aspectRatio:v!.value.aspectRatio,child:Stack(alignment:Alignment.bottomCenter,children:[VideoPlayer(v!),if(current!=null)Container(color:Colors.black87,padding:const EdgeInsets.all(10),child:Text(translated&&current!.translated.isNotEmpty?current!.translated:current!.text,textAlign:TextAlign.center,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)))])),if(v!=null&&v!.value.isInitialized)Row(mainAxisAlignment:MainAxisAlignment.center,children:[IconButton(onPressed:()=>setState(()=>v!.value.isPlaying?v!.pause():v!.play()),icon:Icon(v!.value.isPlaying?Icons.pause:Icons.play_arrow)),Text('${v!.value.position.inSeconds}s')]),TextField(decoration:const InputDecoration(labelText:'Backend URL (tanpa API key)',hintText:'https://domain-backend-anda.com'),onChanged:(x)=>url=x),const SizedBox(height:12),Wrap(spacing:8,children:[ElevatedButton.icon(onPressed:pickVideo,icon:const Icon(Icons.video_file),label:const Text('Pilih Video')),ElevatedButton.icon(onPressed:pickSub,icon:const Icon(Icons.subtitles),label:const Text('Pilih Subtitle'))]),const SizedBox(height:12),ElevatedButton.icon(onPressed:busy?null:translateAll,icon:const Icon(Icons.translate),label:Text(busy?'Memproses...':'Terjemahkan Jepang → Indonesia')),const SizedBox(height:8),Text(status),const SizedBox(height:12),if(cues.isNotEmpty)Text('${cues.length} cue • ${translated?'Terjemahan tersedia':'Bahasa asli'}'),...cues.take(30).map((x)=>ListTile(title:Text(x.translated.isNotEmpty?x.translated:x.text),subtitle:Text('${x.start.inSeconds}s → ${x.end.inSeconds}s')))]));}}
